"""Case repository model.

This is the schema Team 1 depends on (PRD §9: "the case schema must be
frozen by end of Week 2"). See ``docs/API_CONTRACT.md`` for the read
contract exposed to other modules, and ARCHITECTURE.md ADR-02 for why this
lives in Postgres rather than MongoDB.
"""
from __future__ import annotations

import datetime as dt
import enum

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class CaseType(str, enum.Enum):
    """Taxonomy derived from document analysis of existing casebooks
    (Requirements Gathering Document, §4, Day 3 session)."""

    PROFITABILITY = "PROFITABILITY"
    MARKET_ENTRY = "MARKET_ENTRY"
    MERGERS_ACQUISITIONS = "MERGERS_ACQUISITIONS"
    PRICING = "PRICING"
    OPERATIONS = "OPERATIONS"
    OTHER = "OTHER"


class Difficulty(str, enum.Enum):
    """Three difficulty levels, per RGD §4 (Day 3 session output)."""

    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"


class Case(Base):
    __tablename__ = "cases"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Nullable so a case can outlive its owner's account (ADR-03).
    owner_id: Mapped[int | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    owner_deleted: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    title: Mapped[str] = mapped_column(String(255), nullable=False)
    # `name=` is pinned explicitly (rather than left to SQLAlchemy's
    # default) so the Postgres native ENUM type name always matches what
    # alembic/versions/0001_initial_schema.py creates — that migration is
    # hand-written, not autogenerated, so nothing reconciles this
    # automatically if the two ever drift.
    case_type: Mapped[CaseType] = mapped_column(SAEnum(CaseType, name="casetype"), nullable=False, index=True)
    difficulty: Mapped[Difficulty] = mapped_column(SAEnum(Difficulty, name="difficulty"), nullable=False, index=True)
    industry: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    tags: Mapped[list[str]] = mapped_column(JSON, default=list, nullable=False)

    # Storage reference — see app/services/storage.py. Stores a storage key,
    # not a filesystem path, so swapping local disk for GCS (per the
    # architecture doc) later is a storage-service change, not a schema one.
    storage_key: Mapped[str] = mapped_column(String(512), nullable=False)
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    file_size_bytes: Mapped[int] = mapped_column(Integer, nullable=False)

    # Private by default (US-04B AC); sharing is an explicit action.
    is_shared: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    shared_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Admin moderation (FR-11, ADR-05) — soft delete so removed content
    # stays auditable instead of vanishing.
    is_removed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    removal_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Supports FR-08 "sort by most practised" and is the integration point
    # for Team 1 (AI Trainer) to report practice events back — see
    # docs/API_CONTRACT.md, POST /cases/{id}/practice.
    practice_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: dt.datetime.now(dt.timezone.utc), nullable=False, index=True
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: dt.datetime.now(dt.timezone.utc),
        onupdate=lambda: dt.datetime.now(dt.timezone.utc),
        nullable=False,
    )

    # See app/models/user.py for why the target class is passed as an
    # explicit string rather than relying on the Mapped[] annotation alone.
    owner: Mapped["User | None"] = relationship("User", back_populates="cases")
