"""initial schema: users, profiles, cases

Revision ID: 0001
Revises:
Create Date: 2026-07-28

Hand-written (not autogenerated) to mirror app/models/*.py exactly, since
this environment could not run `alembic revision --autogenerate` — keep
this file and the models in sync by hand until CI can regenerate it.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True, index=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("verification_token", sa.String(64), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "target_firm_type",
            sa.Enum("CONSULTING", "PRODUCT_MANAGEMENT", name="targetfirmtype"),
            nullable=True,
        ),
        sa.Column("case_preferences", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("owner_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column(
            "case_type",
            sa.Enum(
                "PROFITABILITY",
                "MARKET_ENTRY",
                "MERGERS_ACQUISITIONS",
                "PRICING",
                "OPERATIONS",
                "OTHER",
                name="casetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty"),
            nullable=False,
        ),
        sa.Column("industry", sa.String(100), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False, server_default="[]"),
        sa.Column("storage_key", sa.String(512), nullable=False),
        sa.Column("original_filename", sa.String(255), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("shared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_removed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("removal_reason", sa.Text(), nullable=True),
        sa.Column("practice_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_cases_case_type", "cases", ["case_type"])
    op.create_index("ix_cases_difficulty", "cases", ["difficulty"])
    op.create_index("ix_cases_industry", "cases", ["industry"])
    op.create_index("ix_cases_created_at", "cases", ["created_at"])


def downgrade() -> None:
    op.drop_table("cases")
    op.drop_table("profiles")
    op.drop_table("users")

    bind = op.get_bind()
    sa.Enum(name="casetype").drop(bind, checkfirst=True)
    sa.Enum(name="difficulty").drop(bind, checkfirst=True)
    sa.Enum(name="targetfirmtype").drop(bind, checkfirst=True)
